apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enrollmenthub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/IngKendrys/bootcamp-arquitecto-ia-cloud-native-copilot-2026.git
    targetRevision: lab-10
    path: infra/helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
