"""add_status

Revision ID: 44a35610e311
Revises: 3fccfc3c8488
Create Date: 2026-03-21 02:11:12.596908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a35610e311'
down_revision: Union[str, None] = '3fccfc3c8488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'items',
        sa.Column('status', sa.String(length=20), nullable=False, server_default='active')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'status')
    # ### end Alembic commands ###
