{
 "title": "Bootcamp API - Observabilidad Base",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"dotnet-api\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "p95 Latencia (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Errores 5xx/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5..\"}[1m]))",
     "legendFormat": "5xx/s"
    }
   ]
  },
  {
   "title": "Requests por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (method, controller, action, code) (rate(http_requests_received_total[1m]))",
     "legendFormat": "{{method}} {{controller}}/{{action}} {{code}}"
    }
   ]
  },
  {
   "title": "Latencia p95 por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method, controller, action) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{method}} {{controller}}/{{action}}"
    }
   ]
  }
 ]
}